//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodLog
    {
        public int fLogID { get; set; }
        public string username { get; set; }
        public Nullable<int> protein { get; set; }
        public Nullable<int> carbs { get; set; }
        public Nullable<int> fat { get; set; }
        public Nullable<int> calories { get; set; }
        public Nullable<System.DateTime> foodDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
