//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.foodLogs = new HashSet<foodLog>();
            this.workoutLogs = new HashSet<workoutLog>();
        }
    
        public string username { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string phoneNum { get; set; }
        public bool gender { get; set; }
        public System.DateTime DOB { get; set; }
    
        public virtual ICollection<foodLog> foodLogs { get; set; }
        public virtual ICollection<workoutLog> workoutLogs { get; set; }
    }
}
