//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class workoutLog
    {
        public workoutLog()
        {
            this.setsLogs = new HashSet<setsLog>();
        }
    
        public int workoutLogID { get; set; }
        public string username { get; set; }
        public string muscleGroup { get; set; }
        public string excercise { get; set; }
        public Nullable<int> wSets { get; set; }
        public Nullable<System.DateTime> wDate { get; set; }
    
        public virtual ICollection<setsLog> setsLogs { get; set; }
        public virtual User User { get; set; }
    }
}
