//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthLogEntities : DbContext
    {
        public HealthLogEntities()
            : base("name=HealthLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<foodLog> foodLogs { get; set; }
        public virtual DbSet<setsLog> setsLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<workoutLog> workoutLogs { get; set; }
    }
}
